services:
    db:
      image: postgres:alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: changeme          # don't do this
        PGUSER: postgres                     # don't do this
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 1s
        timeout: 5s
        retries: 10
        
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
